# Generated by Django 3.2.15 on 2022-09-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('other_party', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('particulars', models.CharField(max_length=200)),
                ('analysis_code', models.CharField(max_length=200)),
                ('trans_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
