# Generated by Django 3.2.15 on 2022-11-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classify_as', models.CharField(max_length=200)),
                ('always_report', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationRegex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=200)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.classification')),
            ],
        ),
    ]
