# Generated by Django 3.2.16 on 2022-11-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_classification_classificationregex'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='classifications',
            field=models.ManyToManyField(to='transactions.Classification'),
        ),
    ]
